### ISSUE TITLE
quitar codigo comentado

### ISSUE THREAD

**Issue by lalo73** [uis2015s1/cumpleaniero#2]
El codigo a continuacion creo que en realidad esta bien planteado(correspondiente a UserHomeTest):

	@Test
	def itUpdatesAUser() {
		this.home.addUser(user)
		var updatedUser = makeValid(new User(this.userName))
		assertFalse(this.home.users.get(0).participates) 
		this.home.updateUser(updatedUser)
		assertTrue(this.home.users.get(0).participates)
	}

Habia un comentario:
"makeValid hizo que el participates de user sea true. Por lo tanto el assert es inválido."

El cual creo no es correcto.

cuando hago "this.home.addUser(user)" estoy agregando una instancia de User que fue creada en el Before annotation, pero luego hago "makeValid(new User(this.userName))" y creo una _nueva_ instancia de User, el cual no esta en el home, el cual su unica referencia es la variable local que hay ahi. (i.e. "updatedUser").

Lo unico que comparten esas dos instancias son el nombre, q el test lo que quiere lograr es forzarte a q busques en el home por _nombre_, no por id, o igualdad de referencia (i.e. "==" )

En cuanto a:

    @Test //(Mismo caso que el de arriba para este)
    def itRaiseExceptionIfUserIsNotInHomeAUser() {
		var updatedUser = makeValid(new User(this.userName))
		assertFalse(this.home.users.get(0).participates)
		try {
			this.home.updateUser(updatedUser)
			fail("UserDoesNotExist expected.");	
		} catch(UserDoesNotExist e) {
			//pass
		}
	}

No entiendo cual es el error.

**Comment by nahuelbe** [comment]
>Lo unico que comparten esas dos instancias son el nombre, q el test lo que quiere lograr es >forzarte a q busques en el home por nombre, no por id, o igualdad de referencia (i.e. "==" )

Justamente eso me había sonado chocante, por eso dejé el comentario. En tal caso está bien entonces! Cierro el issue.
